### ISSUE TITLE
Publish ES5 compat. build

### ISSUE THREAD

**Issue by DSchau** [sebald/spectacle-theme-nova#5]
Hey!

I haven't actually gotten this theme to work quite right yet (still want to do some more testing to verify it's not on my end), but one thing I did notice is that `./lib/index.js` is not transpiled to ES5, and so makes it slightly harder to consume by the end user.

Any chance we could move lib to src/ and then create a transpiled dist/ as part of the build step?

I'd be open to opening up a PR when I get some time, as well, if you're open to it.

Thanks and great job!

**Comment by sebald** [comment]
Hey Dustin,

glad you like the theme 🙂 Everything in the `lib` folder is ES2015 by design (see [note in the reamde](https://github.com/sebald/spectacle-theme-nova#important-note)). But there is also a transpiled version available. Importing `'spectacle-theme-nova/bundle'` should give you a ES5 compatible version. Although, the bundle is not "browser-ready". The output is a CJS module.

If you have any trouble let me know. If you can post an error message/stacke trace would be nice :)
To be honest, I myself never used the bundled version. I am only using this theme in conunction with  [melodrama](https://github.com/sebald/melodrama).

If the bundled version is not easy to use, let me know an we figure something out that is better suited for the use with ES5!

**Comment by sebald** [comment]
@DSchau did you resolve your issue? :)

**Comment by DSchau** [comment]
Had a busy weekend, but I will revisit this week! Feel free to close the issue until I can provide better information!

Thanks!
